type User {
  _id: String
  name: String
  password: String
  phone: String
}

query getUsers {
  users {
    ...UserFields
  }
}

fragment UserFields on User {
  _id
  name
  password
  phone
}

type Query {
  users: [User]
}
